;;;; bsp-viewer.import.scm - GENERATED BY CRUNCH 0.1 -*- Scheme -*-

(begin
  (##sys#with-environment
    (lambda ()
      (##sys#register-compiled-module
        'bsp-viewer
        '#f
        (scheme#list)
        '((main . bsp-viewer#main))
        (scheme#list)
        (scheme#list)
        (scheme#list))))
  (if (memq #:crunched ##sys#features)
    (begin
      (crunch.compiler#declare-entity
        'bsp-viewer#main
        '(procedure
           (integer (pointer (pointer char)) (pointer (pointer char)))
           void)
        'main))))

;; END OF FILE
