;;;; bsp-viewer.import.scm - GENERATED BY CHICKEN 6.0.0pre2 -*- Scheme -*-

(##sys#with-environment
  (lambda ()
    (##sys#register-compiled-module
      'bsp-viewer
      'bsp-viewer
      (scheme#list)
      '((init . bsp-viewer#init)
        (step . bsp-viewer#step)
        (run . bsp-viewer#run)
        (shutdown . bsp-viewer#shutdown)
        (load-bsp . bsp-viewer#load-bsp)
        (models-count . bsp-viewer#models-count)
        (start-loop! . bsp-viewer#start-loop!)
        (stop-loop! . bsp-viewer#stop-loop!))
      (scheme#list)
      (scheme#list)
      (scheme#list))))

;; END OF FILE
